// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "You can take JWT tokens with your username and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Admin login",
                "parameters": [
                    {
                        "description": "Username and password",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "password": {
                                    "type": "string"
                                },
                                "username": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "token": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/league/fixtures": {
            "get": {
                "description": "It returns the entire match schedule for 6 weeks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "All fixtures",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "fixtures": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/model.Match"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/league/next-week": {
            "post": {
                "description": "It simulates next week's matches and updates the league table.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Play next week",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.WeekResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/league/play-all": {
            "post": {
                "description": "Plays through all remaining weeks and returns results for each week.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Play all remaining weeks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PlayAllResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/league/predictions": {
            "get": {
                "description": "Returns each team's championship percentage starting from week 4.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Championship predictions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "predictions": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/service.TeamPrediction"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/league/reset": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "It deletes all matches, resets the standings, and recreates the fixtures.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Reset the league (Admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "status": {
                                    "$ref": "#/definitions/model.LeagueStatus"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/league/status": {
            "get": {
                "description": "Returns the current state of the league (not_started, in_progress, finished)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "League status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LeagueStatus"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/league/table": {
            "get": {
                "description": "Returns a league table sorted according to Premier League rules.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Scoreboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "standings": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/model.Standing"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/league/week/{weekNo}": {
            "get": {
                "description": "It returns the matches of the specified week.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Week details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Week number (1-6)",
                        "name": "weekNo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "matches": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/model.Match"
                                    }
                                },
                                "week": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/match/{id}": {
            "get": {
                "description": "Returns match details based on ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Match details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "match": {
                                    "$ref": "#/definitions/model.Match"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/match/{id}/result": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "It updates the score of a played match and recalculates the league table.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Match result update (Admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New Score",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "away_goals": {
                                    "type": "integer"
                                },
                                "home_goals": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "match": {
                                    "$ref": "#/definitions/model.Match"
                                },
                                "message": {
                                    "type": "string"
                                },
                                "standings": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/model.Standing"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.LeagueStatus": {
            "type": "object",
            "properties": {
                "current_week": {
                    "type": "integer"
                },
                "league_finished": {
                    "type": "boolean"
                },
                "matches_left": {
                    "type": "integer"
                },
                "matches_played": {
                    "type": "integer"
                },
                "status": {
                    "description": "\"not_started\", \"in_progress\", \"finished\"",
                    "type": "string"
                },
                "total_weeks": {
                    "type": "integer"
                }
            }
        },
        "model.LeagueSummary": {
            "type": "object",
            "properties": {
                "best_defense_team": {
                    "type": "string"
                },
                "champion": {
                    "$ref": "#/definitions/model.Standing"
                },
                "final_standings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Standing"
                    }
                },
                "top_scorer_team": {
                    "type": "string"
                },
                "total_goals": {
                    "type": "integer"
                },
                "total_matches": {
                    "type": "integer"
                }
            }
        },
        "model.Match": {
            "type": "object",
            "properties": {
                "away_goals": {
                    "type": "integer"
                },
                "away_team": {
                    "$ref": "#/definitions/model.Team"
                },
                "away_team_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "home_goals": {
                    "type": "integer"
                },
                "home_team": {
                    "description": "Relationships",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Team"
                        }
                    ]
                },
                "home_team_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "played": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "week": {
                    "type": "integer"
                }
            }
        },
        "model.PlayAllResult": {
            "type": "object",
            "properties": {
                "summary": {
                    "$ref": "#/definitions/model.LeagueSummary"
                },
                "total_weeks_played": {
                    "type": "integer"
                },
                "weeks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.WeekResult"
                    }
                }
            }
        },
        "model.Standing": {
            "type": "object",
            "properties": {
                "drawn": {
                    "type": "integer"
                },
                "goal_diff": {
                    "type": "integer"
                },
                "goals_against": {
                    "type": "integer"
                },
                "goals_for": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lost": {
                    "type": "integer"
                },
                "played": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "team": {
                    "description": "Relationships",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Team"
                        }
                    ]
                },
                "team_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "won": {
                    "type": "integer"
                }
            }
        },
        "model.Team": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "strength": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.WeekResult": {
            "type": "object",
            "properties": {
                "league_finished": {
                    "type": "boolean"
                },
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Match"
                    }
                },
                "message": {
                    "type": "string"
                },
                "predictions": {},
                "standings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Standing"
                    }
                },
                "week": {
                    "type": "integer"
                }
            }
        },
        "service.TeamPrediction": {
            "type": "object",
            "properties": {
                "current_points": {
                    "type": "integer"
                },
                "max_points": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                },
                "team_id": {
                    "type": "integer"
                },
                "team_name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT token. Format: \"Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "League Simulation API",
	Description:      "A four-team football league simulation API. Match simulation, league table, and championship prediction based on Premier League rules.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
